//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gapharmaEntities1 : DbContext
    {
        public gapharmaEntities1()
            : base("name=gapharmaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CABECERA_DOCUMENTO> CABECERA_DOCUMENTO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<DESTINATARIO> DESTINATARIO { get; set; }
        public virtual DbSet<DETALLE_DOCUMENTO> DETALLE_DOCUMENTO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<HOJA_DE_RUTA> HOJA_DE_RUTA { get; set; }
        public virtual DbSet<LUGAR_DE_ENTREGA> LUGAR_DE_ENTREGA { get; set; }
        public virtual DbSet<MARCA_MODELO> MARCA_MODELO { get; set; }
        public virtual DbSet<PAQUETE> PAQUETE { get; set; }
        public virtual DbSet<PERMISO> PERMISO { get; set; }
        public virtual DbSet<RUTA> RUTA { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TIPO_VEHICULO> TIPO_VEHICULO { get; set; }
        public virtual DbSet<TRANSPORTISTA> TRANSPORTISTA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CLIENTE_DESTINATARIO> CLIENTE_DESTINATARIO { get; set; }
        public virtual DbSet<PERMISO_USUARIO> PERMISO_USUARIO { get; set; }
        public virtual DbSet<TIPO_DE_CARGA> TIPO_DE_CARGA { get; set; }
        public virtual DbSet<TIPO_RUTA> TIPO_RUTA { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
    }
}
