//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABECERA_DOCUMENTO
    {
        public int CABECERA_DOCUMENTO_ID { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public System.DateTime FECHA_RETIRO { get; set; }
        public int CLIENTE_ID { get; set; }
        public int DESTINATARIO_ID { get; set; }
        public int ESTADO_ID { get; set; }
        public int SERVICIO_ID { get; set; }
        public int EMPRESA_ID { get; set; }
        public int TIPO_DOCUMENTO_ID { get; set; }

        public List<DETALLE_DOCUMENTO> detalle { get; set; }
    }
}
