//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATARIO
    {
        public int DESTINATARIO_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DIRECCION_ENTREGA { get; set; }
        public Nullable<int> CODIGO_POSTAL { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public int PERSONA_ID { get; set; }
    }
}
