//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_DOCUMENTO
    {
        public int DETALLE_DOCUMENTO_ID { get; set; }
        public int CABECERA_DOCUMENTO_ID { get; set; }
        public int PAQUETE_ID { get; set; }
        public int CANTIDAD { get; set; }
    }
}
