//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int EMPLEADO_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public int HABILITADO { get; set; }
        public Nullable<int> EMPRESA_ID { get; set; }
        public int PERSONA_ID { get; set; }
    }
}
