//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public int EMPRESA_ID { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public int CUIL { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO1 { get; set; }
        public int TELEFONO2 { get; set; }
        public string LOCALIDAD { get; set; }
        public string CIUDAD { get; set; }
    }
}
