//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_DE_RUTA
    {
        public int HOJA_DE_RUTA_ID { get; set; }
        public Nullable<int> TRANSPORTISTA_ID { get; set; }
        public Nullable<int> TIPO_DE_CARGA_ID { get; set; }
        public Nullable<int> VEHICULO_ID { get; set; }
        public Nullable<int> RUTA_ID { get; set; }
        public Nullable<int> ESTADO_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<System.DateTime> HORA_INICIO { get; set; }
        public Nullable<System.DateTime> HORA_FIN { get; set; }
        public Nullable<double> KM_INICIO { get; set; }
        public Nullable<double> KM_FIN { get; set; }
        public Nullable<double> KM_RECORRIDOS { get; set; }
        public Nullable<int> ORDEN_DEL_ENVIO { get; set; }
    }
}
