//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE
    {
        public int PAQUETE_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public double PESO { get; set; }
        public double ALTO { get; set; }
        public double ANCHO { get; set; }
        public double PROFUNDIDAD { get; set; }
        public Nullable<int> TIPO_DE_CARGA_ID { get; set; }
    }
}
