//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int PERSONA_ID { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public string LOCALIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string EMAIL { get; set; }
        public  int TELEFONO_1 { get; set; }
        public  int TELEFONO_2 { get; set; }
        public int CODIGO_POSTAL { get; set; }
    }
}
