//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTA
    {
        public int RUTA_ID { get; set; }
        public Nullable<int> LUGAR_ENTREGA_ID { get; set; }
        public Nullable<int> ESTADO_ID { get; set; }
        public int HOJA_DE_RUTA_ID { get; set; }
        public Nullable<int> TIPO_RUTA_ID { get; set; }
    }
}
