//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DE_CARGA
    {
        public int TIPO_DE_CARGA_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<bool> REFRIGERADO { get; set; }
    }
}
