//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gapharma_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public int VEHICULO_ID { get; set; }
        public Nullable<int> TIPO_VEHICULO_ID { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public Nullable<double> CAPACIDAD_TOTAL { get; set; }
        public string PATENTE { get; set; }
        public Nullable<double> KM_ACTUAL { get; set; }
        public Nullable<int> ESTADO_ID { get; set; }
        public Nullable<int> ZONAS_ID { get; set; }
    }
}
